# Generated by Django 5.2.5 on 2025-08-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PdfTopicMap",
            fields=[
                (
                    "document_id",
                    models.UUIDField(
                        blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("pdf_name", models.CharField(max_length=255)),
                ("topic", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "pdf_topic_map",
                "permissions": (
                    ("access_pdf", "Can access this document"),
                    ("edit_pdf", "Can edit this document"),
                ),
                "indexes": [
                    models.Index(
                        fields=["pdf_name"], name="pdf_topic_m_pdf_nam_1e9e48_idx"
                    ),
                    models.Index(fields=["topic"], name="pdf_topic_m_topic_24aa23_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pdf_name", "topic"), name="uq_pdf_topic"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="QARecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "qa_record",
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="qa_record_created_612096_idx"
                    )
                ],
            },
        ),
    ]
